baseURL = "https://avocadotest.com/"
languageCode = "en-us"
title = "Avocado Test"
theme = "docsy"

[params]
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Avocado Test"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "such as test"
    github_repository = "https://github.com/pfd/avocado-test/"
    version = "0.0.1"



    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "GTM-5VQ5MXS" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "entry", "post"]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/pfd"
    weight = 2

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 3